name: Deploy Slides
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '24' # On passe à la version 24 pour stopper l'alerte
          
      - name: Install Dependencies
        run: npm install

      - name: Build Slides
        run: npx slidev build slides.md --base /impression3D/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist